s3 backend management
Caascad/tf pull request #36
Opened 2020-06-06 20:54 UTC by Benjile

* Generate terraform backend
* use sts to get temporary aksk from vault

2020-06-18 09:16 UTC, eonpatapon commented on tf
> +    BACKEND_CONFIG="-backend-config=access_key=${TF_BACKEND_ACCESS_KEY} -backend-config=secret_key=${TF_BACKEND_SECRET_KEY} -backend-config=session_token=${TF_BACKEND_SESSION_TOKEN}"
```suggestion
    echo "-backend-config=access_key=${TF_BACKEND_ACCESS_KEY} -backend-config=secret_key=${TF_BACKEND_SECRET_KEY} -backend-config=session_token=${TF_BACKEND_SESSION_TOKEN}"
```

2020-06-18 09:17 UTC, eonpatapon commented on tf
> +  _tf_generic init -upgrade=true ${BACKEND_CONFIG}
```suggestion
  _tf_generic init -upgrade=true $(_tf_backend_config)
```

2020-06-18 09:17 UTC, eonpatapon commented on tf
> +	BACKEND_CONFIG=$(_tf_backend_config)
```suggestion
```

2020-06-18 09:18 UTC, eonpatapon commented on tf
> +
Indent is off

2020-07-03 12:31 UTC, yesteph commented on tf
> +    region = "${TF_BACKEND_BUCKET_REGION_NAME}"
Set dynamodb_table is not empty

2020-07-03 12:32 UTC, yesteph commented on tf
> +TF_BACKEND_BUCKET_REGION_NAME="us-east-2"
Manage a TF_BACKEND_DYNAMODB_TABLE_NAME variable.

2020-09-18 12:30 UTC, Benjile commented on tf
> +TF_BACKEND_BUCKET_REGION_NAME="us-east-2"
done

2020-09-18 12:31 UTC, Benjile commented on tf
> +    region = "${TF_BACKEND_BUCKET_REGION_NAME}"
i added the dynamodb attribute

2020-09-18 13:18 UTC, eonpatapon requested changes

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +  # set vault url, we must be able to override the vault url provided by caascad zones
Why ?

I think this will be a source of trouble if you use VAULT_ADDR of the user environment

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +    curl -s -o "${TF_CAASCAD_ZONES_FILE}" "${CAASCAD_ZONES_URL}"
Maybe add `--connect-timeout` and fail with an error message

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +  if [[ $? -ne 0 ]]; then log_error "cannot find zone ${ENVIRONMENT} in caascad-zones.json file."; fi
This code won't be reached as we use `set -e`

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +  if [[ $? -ne 0 ]]; then log_error "cannot find zone ${ENVIRONMENT} in caascad-zones.json file."; fi
```suggestion
if ! jq -r -e --arg zone  "${ENVIRONMENT}" '.[$zone].name' < "${TF_CAASCAD_ZONES_FILE}" > /dev/null
then
  # shellcheck disable=2181
  log_error "cannot find zone ${ENVIRONMENT} in caascad-zones.json file."
fi
```

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +  echo "$VALUE"
```suggestion
  jq -r ".\"$ZONE\".$KEY" < "${TF_CAASCAD_ZONES_FILE}"
```

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +  TF_BACKEND_BUCKET_SUFFIX="${TF_BACKEND_BUCKET_SUFFIX:-${TF_BACKEND_BUCKET_DEFAULT_SUFFIX}}"
Why not putting all of this at the top then ?

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +  LIB_URL="${LIB_URL:-${LIB_URL_DEFAULT}}"
Same as below

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +    token=$(VAULT_ADDR=${VAULT_ADDR} vault read "${AWS_STS_PATH}" -format=json)
```suggestion
    token=$(vault read "${AWS_STS_PATH}" -format=json)
```

2020-09-18 13:18 UTC, eonpatapon commented on tf
> +  # generate backend file
Not sure why it is optional ?

2020-09-18 13:35 UTC, Benjile commented on tf
> +  # set vault url, we must be able to override the vault url provided by caascad zones
during a bootstrap process we should be able to override the VAULT_ADDR used

2020-09-18 14:18 UTC, Benjile commented on tf
> +    token=$(VAULT_ADDR=${VAULT_ADDR} vault read "${AWS_STS_PATH}" -format=json)
it won't work as we do not export this variable

2020-09-18 14:18 UTC, Benjile commented on tf
> +    token=$(VAULT_ADDR=${VAULT_ADDR} vault read "${AWS_STS_PATH}" -format=json)
i tested it :-)

2020-09-18 14:20 UTC, Benjile commented on tf
> +  # generate backend file
a feature to not override a backend.tf provided in the configuration, or just to work locally

2020-09-22 14:27 UTC, eonpatapon requested changes

2020-09-22 14:27 UTC, eonpatapon commented on default.nix
> +    wrapProgram $out/bin/tf --prefix PATH : "${lib.makeBinPath [ findutils gnused coreutils jq curl ]}"
vault missing

2020-09-22 14:27 UTC, eonpatapon commented on tf
> +  # set vault url, we must be able to override the vault url provided by caascad zones
I woul prefer to allow to override it from tffile, but not from the env

2020-09-24 14:07 UTC, Benjile commented on tf
> +  # set vault url, we must be able to override the vault url provided by caascad zones
at the beginning of the of the parse function we have a source tffile, so i will add before an unset VAULT_ADDR to fulfill your request

2020-09-24 14:46 UTC, Benjile commented on default.nix
> +    wrapProgram $out/bin/tf --prefix PATH : "${lib.makeBinPath [ findutils gnused coreutils jq curl ]}"
fixed

2020-09-25 09:07 UTC, eonpatapon approved these changes

2020-09-28 07:11 UTC, merged